lottie_url1: "https://lottie.host/f89e48e2-55e5-4fdf-a406-0be2b00cc2af/ECJa6PGrCV.json"
lottie_url2: "https://lottie.host/05824020-0a23-4373-8418-721bd6e68504/FE5XXRT455.json"
welcome_template: "Data Analyst Assistant is an advanced, open-source application powered by LLMs like GPT-4/GPT-3.5-turbo that streamlines the entire process of data analysis. It automates all the tasks from data preprocessing to model testing, simplifying complex data tasks with precision."
introduction_template1: |
  As a data analysis agent, **Data Analysis Assistant** is capable of making autonomous decisions based on your data:
  - Effortless Data Preprocessing
  - Intelligent Encoding & Balancing
  - Automated Model Selection & Training
  - Dynamic Data Visualization
  - And much more...
introduction_template2: |
  **You only need to**:
  1. **Select** your data file
  2. **Choose** an analysis mode
  3. **Press** the Start button